### PR TITLE
feat: support RN 0.76 + add example with RNTA

### PR DESCRIPTION
**Pull request by vonovak**
## Summary

same as #537 but also includes an example app that uses [react-native-test-app](https://github.com/microsoft/react-native-test-app). You can take it, or ignore it - up to you.

used `npx --package react-native-test-app@latest init` to create the example. Then copied over the src folder from the old example.

## Test Plan

```
cd rnta-example
yarn install
npx patch-package
cd ios && npx pod-install && cd -
```

There's a patch for react-native-screens taken from https://github.com/software-mansion/react-native-screens/pull/2407/files#diff-59c313fb0dfe322996885368a5a90d8f8400c2576bb64acc60467c2e79ecd2e9

then build as ususal

### CODE REVIEW

**Comment by janicduplessis** [comment]
This looks great, gonna take some time to properly review and test in a few days.

**Comment by vonovak** [comment]
Android build failure will be resolved by using https://github.com/software-mansion/react-native-screens/releases/tag/4.0.0-beta.13

**Comment by janicduplessis** [comment]
@vonovak Looks like rn-screens released a stable version with 0.76 support [3.35.0](https://github.com/software-mansion/react-native-screens/releases/tag/3.35.0).

Could you fix the conflicts then I think we can merge this.

**Comment by janicduplessis** [comment]
I also have some report of the build still failing on android (https://github.com/th3rdwave/react-native-safe-area-context/issues/542), if you have the chance could you also check if the new example app works on android?

**Comment by vonovak** [comment]
@janicduplessis I installed the .76 - compatible deps and CI is passing. However, I removed the macos example which was just recently added.
RN macos is a one version behind now, and I'm not sure how well it'll play to have multiple versions of react and etc in one place. Maybe it will work, maybe it won't, maybe there should be 2 examples so that android+ios can run in separation from macos (I'd prefer that)? I felt it's more up to you to decide.

**Comment by janicduplessis** [comment]
Since rn macos always seem to he a bit behind rn versions I think we will have to have a different example app sadly.

**Review by janicduplessis — APPROVED** [review]

**Pull request merged**
