### PR TITLE
Add mocks for hooks to jest/mock.js

### PR DESCRIPTION
**Pull request by cp**
## Summary

Building off the mocks added [here](https://github.com/th3rdwave/react-native-safe-area-context/commit/9fa4cb8182388832a44238001fdc2bd35f02a1ca#diff-88fd4d6b6eb56e14365572f91f687a7946cf775b419cd1afcdd2dcd71d33b1fa), this PR adds mocks for the `useSafeAreaInsets` and `useSafeAreaFrame` hooks.

## Test Plan

I do not see any tests for this file. Open to feedback here, of course!

### CODE REVIEW

**Review by miallo — APPROVED** [review]
Looks good :+1:

**Comment by WillyRamirez** [comment]
Would be nice if this can be merged!

**Review by miallo — APPROVED** [review]

**Comment by DannyBiezen** [comment]
I'm currently mocking this myself manually but it would be great if this was included!

**Comment by jacobp100** [comment]
@janicduplessis any reason not to merge this?

**Comment by jacobp100** [comment]
@cp Could you resolve conflicts?

**Review by jacobp100 — APPROVED** [review]

**Comment by cp** [comment]
@jacobp100 I just merged main in to resolve conflicts!

**Pull request merged**
