### PR TITLE
Add support for getting initial safe area insets on mount

### PR DESCRIPTION
**Pull request by jacobp100**
## Summary

Adds support for getting initial safe area insets on mount. See #26 

## Test Plan

`console.log` of the value on verified this value was correct

### CODE REVIEW

**Comment by janicduplessis** [comment]
@jacobp100 Thanks for working on this! Could you rename this to `initialWindowInsetsSafeAreaInsets` so it's clear that it is insets from the root window and that they can be different from the one returned by the provider (in the case it doesn't cover the screen).

Also what do you think about exposing this as a prop on the provider vs this api?

Something like `initializeWithWindowInsets` maybe? Might be safer so people don't rely on values provided by `initialWindowInsetsSafeAreaInsets` for other things.

**Comment by satya164** [comment]
How about `initialWindowSafeAreaInsets` instead of `initialWindowInsetsSafeAreaInsets`?

> Also what do you think about exposing this as a prop on the provider vs this api?

Does a provider have any advantage instead of an exported constant? I guess this value is not really constant and could change on device orinetation change etc.?

**Comment by janicduplessis** [comment]
@satya164 Oups that was a typo lol, I'll edit my comment.

It would allow not exposing the actual value so people don't use it because it is convenient, since like you said it can change. The provider could use the value internally to initialize itself though. It would still have to be disabled by default since we can't assume the provider covers the screen (for example if you have a provider inside the new ios modal).

**Comment by jacobp100** [comment]
> Could you rename this to initialWindowSafeAreaInsets so it's clear that it is insets

Will do

To me, adding another prop for this feels like increasing the API surface area just so people don't make these incorrect assumptions. We might be better documenting all the cases that affect the safe area insets (also fixes #10), and saying out that it's never safe to rely on this value past the initial mount

Or half way would be we expose it as an opaque object (i.e. `{ __preset: "window" }`) so the user couldn't rely on it

Or we can just do the prop - it's all subjective anyway! Lemmi know what way you wanna go

We should do the docs anyway. I'm happy to do iOS docs. I can take a look at Android and make a best attempt, but I'm pretty unfamiliar with the notch situation there, so might need review

**Comment by janicduplessis** [comment]
Ok let's just rename it to `initialWindowSafeAreaInsets` and go with that. It might be possible to implement on Android using something like `activity.getWindow().getDecorView().getRootWindowInsets()` but we can do that in a follow up.

**Comment by jacobp100** [comment]
Hey sorry for the delay - I didn't get the notification from Github. I've done this change now. I'll try and and look at Android at some point in a future PR

**Comment by janicduplessis** [comment]
@jacobp100 Thanks for this!

**Pull request merged**
