### PR TITLE
fix: fixes for new arch on RN 74

### PR DESCRIPTION
**Pull request by WoLewicki**
## Summary

This PR aligns the code with newest version of `yoga` in RN `0.74.0-rc.0`.  Made with huge help from @piaskowyk

### CODE REVIEW

**Comment by jacobp100** [comment]
Thanks for this! What does this do for older versions? Will they break?

**Comment by WoLewicki** [comment]
On new arch it will for sure. On paper I think those files are not compiled so it should not.

**Comment by jacobp100** [comment]
I think last time we published this as a pre-release, and then waited until it fully drops to publish in full

@janicduplessis

**Comment by janicduplessis** [comment]
Yes, we can do pre-release, I'm fine breaking back compat for new arch still.

**Comment by WoLewicki** [comment]
So let's do it please, it will help with testing it in other libs which use SAC 🚀

**Review by janicduplessis — APPROVED** [review]

**Comment by janicduplessis** [comment]
Looks like this will cause issues even with new arch disabled. The ci build on android fails with old arch and rn 0.73. We will need to find a way to make this backwards compatible. Maybe we can just not compile those classes with some preprocessor macros when on old arch.

**Comment by WoLewicki** [comment]
Yeah, it seems not right that you are trying to compile shadow nodes on old arch.

**Comment by WoLewicki** [comment]
Ok it seems that you are building new arch in both flows now: https://github.com/th3rdwave/react-native-safe-area-context/blob/c9b729343e8e2a73b723a76bae6319b97b121cc6/example/android/gradle.properties#L37 😄

**Pull request merged**
