### PR TITLE
[android] Remove a check that is no longer needed

### PR DESCRIPTION
**Pull request by chrfalch**
## Summary

We've had some issue with monorepos when resolving the codegen config on Android in other libraries, and found that due to versions no longer in use we could now remove the version test in `react-native-config.js` and always return the component descriptor etc.

(The monorepo issue was with using `require.main.require` which will resolve to the calling script and not the module)

For reference, here is the same PR in `@react-native-community/slider`:

https://github.com/callstack/react-native-slider/pull/657

## Test Plan

This will not fix a bug as of now, but is a preparation for later to make sure that the component descriptors are correctly added to the `autolinking.cpp` file.

In `@react-native-community/slider` the following issue was registered: https://github.com/callstack/react-native-slider/issues/652

### CODE REVIEW

**Comment by jacobp100** [comment]
Thanks for this. I'm not too familiar with Android. Janic might know. Otherwise, we might just wait and see what CallStack do with the other PR?

**Comment by janicduplessis** [comment]
I am a bit worried about backwards compat here, could we add a fallback to something like require("../@react-native-community/…") to handle that case? Assuming deps are in the same folder. I would also be open to just setting the default to true so if we cant find the file we assume codegenconfig is supported.

**Comment by chrfalch** [comment]
> I am a bit worried about backwards compat here, could we add a fallback to something like require("../@react-native-community/…") to handle that case? Assuming deps are in the same folder. I would also be open to just setting the default to true so if we cant find the file we assume codegenconfig is supported.

Understand your concerns - but would codegen even be used in an older version of React Native? We could also just change `require.main.require` -> `require` - which also works.

**Comment by chrfalch** [comment]
The corresponding PR was merged in `@react-native-community/slider` now.

**Comment by janicduplessis** [comment]
The problem that this code fixes is that older versions of RN cli do not support the codegen config and throw an error because of that extra config prop sadly.

**Comment by chrfalch** [comment]
> If we want to keep this simple I would be fine just changing the default value so if the file is not found we add the codegen config.

Reverted and added a change to the initial value only as you suggested :)

**Review by vonovak — APPROVED** [review]

**Pull request merged**
